// <auto-generated />
using System;
using MessageWrapperMediatR.Infrastructure.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageWrapperMediatR.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(MessageWrapperMeditaRDbContext))]
    [Migration("20251022074828_MessageWrapperInitialization")]
    partial class MessageWrapperInitialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MessageWrapperMeditaR")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MessageWrapperMediatR.Core.Models.Binding", b =>
                {
                    b.Property<string>("Exchange")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RoutingKey")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("HandlerId")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Exchange", "RoutingKey", "HandlerId");

                    b.HasIndex("HandlerId");

                    b.ToTable("Bindings", "MessageWrapperMeditaR");
                });

            modelBuilder.Entity("MessageWrapperMediatR.Core.Models.CollectedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssociateCommand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FromQueue")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceptionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TimeToLiveInDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7);

                    b.HasKey("Id");

                    b.HasIndex("FromQueue");

                    b.HasIndex("ReceptionDate");

                    b.ToTable("CollectedMessages", "MessageWrapperMeditaR");
                });

            modelBuilder.Entity("MessageWrapperMediatR.Core.Models.Handler", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssociateCommand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("BusType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MessageIsStored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TimeToLiveInDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7);

                    b.HasKey("Id");

                    b.ToTable("Handlers", "MessageWrapperMeditaR");
                });

            modelBuilder.Entity("MessageWrapperMediatR.Core.Models.Binding", b =>
                {
                    b.HasOne("MessageWrapperMediatR.Core.Models.Handler", "Handler")
                        .WithMany("Bindings")
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handler");
                });

            modelBuilder.Entity("MessageWrapperMediatR.Core.Models.Handler", b =>
                {
                    b.Navigation("Bindings");
                });
#pragma warning restore 612, 618
        }
    }
}
